services:
  mail:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - wt

networks:
  wt:

volumes:
  wt_data:
  wt_webtutor:
  wt_logs:
  wt_idxs:
  wt_apps:
  wtdb_postgresql_data:
