version: "3.9"

services:
  wt:
    image: websoft/hcm:2022.2.3.531
    entrypoint: tail -f /dev/null
    volumes:
      - ${pwd}/wt/wt_data:/WebsoftServer/wt_data
      - ${pwd}/wt/wt/web/webtutor:/WebsoftServer/wt/web/webtutor
      - ${pwd}/wt/wet/web/dapi:/WebsoftServer/wt/web/dapi
      - ${pwd}/wt/xhttp_config.json:/WebsoftServer/xhttp_config.json
      - ${pwd}/wt/Logs:/WebsoftServer/Logs
      - ${pwd}/wt/ft-idx:/WebsoftServer/ft-idx
      - ${pwd}/wt/applications:/WebsoftServer/applications
      - ${pwd}/wt/xHttp.ini:/WebsoftServer/xHttp.ini
      - ${pwd}/wt/spxml_unibridge_config.xml:/WebsoftServer/spxml_unibridge_config.xml
    ports:
      - 8080:8011
    depends_on:
      - wtdb
    networks:
      - wt

  wtdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./docker/db/create_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432

networks:
  wt:
  wtdb:

volumes:
  wt:
  wtdb:
