version: "3.9"

services:
  wt:
    build:
      context: ./docker/wt
      dockerfile: Dockerfile

    # volumes:
      # - wt/wt_data:/WebsoftServer/wt_data
      # - wt/wt/web/webtutor:/WebsoftServer/wt_data
      # - wt/wet/web/dapi:/WebsoftServer/wt_data
      # - wt/xhttp_config.json:/WebsoftServer/wt_data
      # - wt:/WebsoftServer/wt_data
      # - wt:/WebsoftServer/wt_data
    #  - ./wt/wt_data:/WebsoftServer/wt_data
    #  - ./wt/wt/web/webtutor:/WebsoftServer/wt/web/webtutor
    #  - ./wt/wt/web/test:/WebsoftServer/wt/web/test
    #  - ./wt/xhttp_config.json:/WebsoftServer/xhttp_config.json
    #  - ./wt/Logs:/WebsoftServer/Logs
    #  - ./wt/ft-idx:/WebsoftServer/ft-idx
    #  - ./wt/applications:/WebsoftServer/applications
    #  - ./wt/xHttp.ini:/WebsoftServer/xHttp.ini
    #  - ./wt/spxml_unibridge_config.xml:/WebsoftServer/spxml_unibridge_config.xml
    ports:
      - 8080:8011
    # depends_on:
    #   - wtdb
    networks:
      - wt

  wtdb:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - 1433:1433
    networks:
      - wtdb
    volumes:
      - wtdb:/var/opt/mssql

networks:
  wt:
  wtdb:

volumes:
  wt:
  wtdb:
