version: "3.9"

services:
  wt:
    image: websoft/hcm:2022.2.3.531
    entrypoint: tail -f /dev/null
    volumes:
      - wt_data:/WebsoftServer/wt_data
      - wt_webtutor:/WebsoftServer/wt/web/webtutor
      - wt_logs:/WebsoftServer/Logs
      - wt_idxs:/WebsoftServer/ft-idx
      - wt_apps:/WebsoftServer/applications
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - wt

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./misc/create_postgresql_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - wtdb_postgresql_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - wt

  mail:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - wt

networks:
  wt:

volumes:
  wt_data:
  wt_webtutor:
  wt_logs:
  wt_idxs:
  wt_apps:
  wtdb_postgresql_data:
