version: "3.9"

services:
  wt:
    image: websoft/hcm:2022.2.3.531
    entrypoint: tail -f /dev/null
    volumes:
      - wt_data/wt_data:/WebsoftServer/wt_data
      - wt_data/wt/web/webtutor:/WebsoftServer/wt/web/webtutor
      - wt_data/Logs:/WebsoftServer/Logs
      - wt_data/ft-idx:/WebsoftServer/ft-idx
      - wt_data/applications:/WebsoftServer/applications
      - wt_data/xHttp.ini:/WebsoftServer/xHttp.ini
      - wt_data/spxml_unibridge_config.xml:/WebsoftServer/spxml_unibridge_config.xml
      - wt_data/xhttp_config.json:/WebsoftServer/xhttp_config.json
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - wt

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./misc/create_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - wtdb_postgresql_data:/var/lib/postgresql/data

    ports:
      - 5433:5432
    networks:
      - wt

  mail:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - wt

networks:
  wt:

volumes:
  wt_data:
  wtdb_postgresql_data:
