version: "3.9"

services:
  wt:
    image: websoft/hcm:2023.1.649_REL
    container_name: wt
    hostname: wt
    entrypoint: ./xhttp.out
    volumes:
     - ./wt/wt_data:/WebsoftServer/wt_data
     - ./wt/wt/web/webtutor:/WebsoftServer/wt/web/webtutor
     - ./wt/wt/web/test:/WebsoftServer/wt/web/test
     - ./wt/xhttp_config.json:/WebsoftServer/xhttp_config.json
     - ./wt/Logs:/WebsoftServer/Logs
     - ./wt/ft-idx:/WebsoftServer/ft-idx
     - ./wt/applications:/WebsoftServer/applications
     - ./wt/xHttp.ini:/WebsoftServer/xHttp.ini
     - ./wt/spxml_unibridge_config.xml:/WebsoftServer/spxml_unibridge_config.xml
    ports:
      - 8080:8011
    depends_on:
      - wtdb
    networks:
      - webtutor

  wtdb:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    hostname: mssql
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - 1433:1433
    networks:
      - webtutor

networks:
  webtutor:
    driver: bridge

volumes:
  webtutor-sql:
