version: "3.9"
services:
  wt:
    image: $WEBTUTOR_IMAGE
    container_name: wt
    hostname: wt
    entrypoint: tail -f ./spxml_unibridge_config.xml
    volumes:
     - ./webtutor/wt_data:/WebsoftServer/wt_data
     - ./webtutor/wt/web/webtutor:/WebsoftServer/wt/web/webtutor
     - ./webtutor/Logs:/WebsoftServer/Logs
     - ./webtutor/ft-idx:/WebsoftServer/ft-idx
     - ./webtutor/applications:/WebsoftServer/applications
     - ./webtutor/xHttp.ini:/WebsoftServer/xHttp.ini
     - ./webtutor/spxml_unibridge_config.xml:/WebsoftServer/spxml_unibridge_config.xml
     - ./config/wt:/usr/config
    ports:
      - 4000:4000
    depends_on:
      # - mssql
      - postgres
      - mailhog
    networks:
      - webtutor

  mailhog:
    image: $MAILHOG_IMAGE
    container_name: mailhog
    hostname: mailhog
    ports:
      - 1080:8025
    networks:
      - webtutor

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    hostname: mssql
    entrypoint:
      - /usr/config/entrypoint.sh
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=zH8vV@a4
    volumes:
      - ./db/data:/var/opt/mssql/data
      - ./db/log:/var/opt/mssql/log
      - ./db/secrets:/var/opt/mssql/secrets
      - ./config/db:/usr/config
    ports:
      - 1433:1433
    networks:
      - webtutor

  # postgres:
  #   image: postgres:14.3
  #   container_name: postgres
  #   hostname: postgres
  #   environment:
  #     POSTGRES_PASSWORD: dev
  #   volumes:
  #     - ./db/postgres/data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - webtutor

networks:
  webtutor:
    driver: bridge
