#!/bin/bash
docker run --restart always -p 80:8011/tcp \
--add-host=wt:192.168.0.48 \
-h `hostname` \
-v ~/WebSoftHCM/docker/WebSoftServerForDocker/wt_data:/WebsoftServer/wt_data \
-v ~/WebSoftHCM/docker/WebSoftServerForDocker/wt/web/webtutor:/WebsoftServer/wt/web/webtutor \
-v ~/WebSoftHCM/docker/WebSoftServerForDocker/Logs:/WebsoftServer/Logs \
-v ~/WebSoftHCM/docker/WebSoftServerForDocker/ft-idx:/WebsoftServer/ft-idx \
-v ~/WebSoftHCM/docker/WebSoftServerForDocker/applications:/WebsoftServer/applications \
-v ~/WebSoftHCM/docker/WebSoftServerForDocker/xHttp.ini:/WebsoftServer/xHttp.ini \
-v ~/WebSoftHCM/docker/WebSoftServerForDocker/spxml_unibridge_config.xml:/WebsoftServer/spxml_unibridge_config.xml \
websoft/hcm:2020.4.3.272 ./xhttp.out &