name: wt-mssql

services:
  wt:
    extends:
      file: wt.yml
      service: wt
    ports:
      - 80:80
    networks:
      - wt

  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - 1434:1433
    networks:
      - wt

  email:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - wt

networks:
  wt:

volumes:
  wt_data:
  wt_webtutor:
  wt_logs:
  wt_idxs:
  wt_apps: