name: wt-mssql-test-db

services:
  wt:
    extends:
      file: wt.yml
      service: wt
    ports:
      - 80:80

  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    volumes:
      - ./misc/backup:/var/opt/mssql/backup
    ports:
      - 1433:1433

  sql-tools:
    image: mcr.microsoft.com/mssql-tools:latest
    # entrypoint: tail -f /dev/null
    entrypoint: /tmp/restore.sh
    volumes:
      - ./misc/restore/:/tmp

  email:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  wt_data:
  wt_webtutor:
  wt_logs:
  wt_idxs:
  wt_apps: