name: wt-mssql-test-db

services:
  wt:
    extends:
      file: wt.yml
      service: wt
    depends_on:
      sql-tools:
        condition: service_completed_successfully
        restart: true
    ports:
      - 80:80

  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    env_file: .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - ./misc/mssql/backup:/var/opt/mssql/backup
    ports:
      - 1433:1433

  sql-tools:
    image: mcr.microsoft.com/mssql-tools:latest
    env_file: .env
    entrypoint: /tmp/restore.sh
    environment:
      - MSSQL_USERNAME=${MSSQL_USERNAME}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - ./misc/mssql/:/tmp

  email:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  wt_data:
  wt_webtutor:
  wt_logs:
  wt_idxs:
  wt_apps: