name: wt-mssql

services:
  wt:
    extends:
      file: wt.yml
      service: wt
    depends_on:
      sql-tools:
        condition: service_completed_successfully
        restart: true
    ports:
      - ${WT_HOST_PORT}:${WT_DOCKER_PORT}

  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    env_file: .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - ./misc/mssql/backup:/var/opt/mssql/backup
    ports:
      - ${MSSQL_HOST_PORT}:${MSSQL_DOCKER_PORT}

  sql-tools:
    image: mcr.microsoft.com/mssql-tools:latest
    env_file: .env
    entrypoint: /tmp/restore.sh
    environment:
      - MSSQL_USERNAME=${MSSQL_USERNAME}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - ./misc/mssql/:/tmp

  email:
    image: axllent/mailpit
    ports:
      - ${MAILPIT_HOST_SMTP_PORT}:${MAILPIT_DOCKER_SMTP_PORT}
      - ${MAILPIT_HOST_UI_PORT}:${MAILPIT_DOCKER_UI_PORT}

volumes:
  wt-data:
    name: "wt-data"
  wt-webtutor:
    name: "wt-webtutor"
  wt-logs:
    name: "wt-logs"
  wt-idxs:
    name: "wt-idxs"
  wt-apps:
    name: "wt-apps"