name: wt-psql

services:
  wt:
    extends:
      file: wt.yml
      service: wt
    ports:
      - 81:80
    networks:
      - wt

  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./misc/create_postgresql_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - wtdb_postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - wt

  email:
    image: axllent/mailpit
    ports:
      - 1026:1025
      - 8026:8025
    networks:
      - wt

networks:
  wt:

volumes:
  wt_data:
  wt_webtutor:
  wt_logs:
  wt_idxs:
  wt_apps:
  wtdb_postgresql_data: