name: wt-postgres

services:
  wt:
    extends:
      file: wt.yml
      service: wt
    ports:
      - 81:80
    networks:
      - wt

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./misc/create.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - wtdb-postgres-data:/var/lib/postgres/data
    ports:
      - 5432:5432
    networks:
      - wt

  email:
    image: axllent/mailpit
    ports:
      - 1026:1025
      - 8026:8025
    networks:
      - wt

networks:
  wt:

volumes:
  wtdb-postgres-data:
    name: "wtdb-postgres-data"