services:
  wt-test:
    image: websoft/hcm:2023.2.868_DEV
    entrypoint: tail -f /dev/null
    volumes:
      - wt_data:/WebsoftServer/wt_data
      - wt_webtutor:/WebsoftServer/wt/web/webtutor
      - wt_logs:/WebsoftServer/Logs
      - wt_idxs:/WebsoftServer/ft-idx
      - wt_apps:/WebsoftServer/applications
    ports:
      - 80:80
    networks:
      - wt
  
  wt-base:
    image: websoft/hcm:2023.2.803_DEV
    entrypoint: tail -f /dev/null
    volumes:
      - wt_data:/WebsoftServer/wt_data
      - wt_webtutor:/WebsoftServer/wt/web/webtutor
      - wt_logs:/WebsoftServer/Logs
      - wt_idxs:/WebsoftServer/ft-idx
      - wt_apps:/WebsoftServer/applications
    ports:
      - 80:80
    networks:
      - wt