services:
  wt:
    image: websoft/hcm:2023.2.916
    entrypoint: tail -f /dev/null
    volumes:
      - wt_data:/WebsoftServer/wt_data
      - wt_webtutor:/WebsoftServer/wt/web/webtutor
      - wt_logs:/WebsoftServer/Logs
      - wt_idxs:/WebsoftServer/ft-idx
      - wt_apps:/WebsoftServer/applications